import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-slate-100 w-full flex justify-between top-0 p-2 fixed">
          <div className="flex">
            <Input type="text" className="w-56"></Input>
            <Button></Button> 
          </div>
          <div>
          <Button></Button>
          <Button></Button>
          <Button></Button>
          <Button></Button>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
